In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score,confusion_matrix

# df = pd.read_csv('Iris.csv')
df = pd.read_csv("Iris.csv")

# X = df.iloc[:,:-1]
X = df.drop(columns=["Class Label"])
y = df['Class Label']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 , random_state = 100)

X_train,y_train

X_test,y_test

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


lda = LinearDiscriminantAnalysis(n_components = 2)
X_train_lda = lda.fit_transform(X_train_scaled,y_train)
X_test_lda = lda.transform(X_test_scaled)

X_train_lda.shape

classifier = LogisticRegression()
classifier.fit(X_train_lda,y_train)
y_pred = classifier.predict(X_test_lda)



accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

print('Accuracy :',accuracy)
print('Confusion matrix :\n',conf_matrix)

Accuracy : 1.0
Confusion matrix :
 [[11  0  0]
 [ 0  6  0]
 [ 0  0 13]]
