In [2]:

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.preprocessing import LabelEncoder 


df = pd.read_csv("car_evaluation.csv")
df

df.describe()

col_names = ['Buying' , 'maint' ,'doors' ,'persons' ,'lug_boot' ,'safety' ,'class']
df.columns = col_names

df.head()


le = LabelEncoder()

for col in df.columns:
    if df[col].dtype != 'object':
        continue

    df[col] = le.fit_transform(df[col])

    
df.head()



X = df.drop(['class'],axis =1)
y = df['class']

X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2,random_state=60)
X_train.shape , X_test.shape




((1382, 6), (346, 6))

In [3]:
rfc = RandomForestClassifier(n_estimators = 18+25)
rfc.fit(X_train,y_train)


y_pred = rfc.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
conf_matrix = confusion_matrix(y_test,y_pred)

print('Accuracy:',accuracy*100,'%','\n')
print('Confusion Matrix:\n',conf_matrix)

Accuracy: 94.50867052023122 % 

Confusion Matrix:
 [[ 73   3  12   0]
 [  1  11   0   0]
 [  3   0 228   0]
 [  0   0   0  15]]
